# -*- coding: utf-8 -*-
"""age_india.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197BazCsswZVBWnPykVPL_0mqeQgS0WFw
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from sklearn.preprocessing import LabelEncoder

data=pd.read_csv('/content/drive/MyDrive/Dataset/Image_data/india/faces/train.csv')
data.head()

la=LabelEncoder()
data['Class']=la.fit_transform(data['Class'])
data

path='/content/drive/MyDrive/Dataset/Image_data/india/faces/Train'
x=[]
y=[]
photo=[]
count=[len(data)]
for i in range(0,500,1):
  id=data['ID'].iloc[i]
  clas=data['Class'].iloc[i]
  path2=os.path.join(path,id)
  img2=cv2.imread(path2)
  if img2 is None:
    continue
  img3=cv2.resize(img2,(128,128))
  x.append(img3)
  photo.append(path2)
  y.append(clas)

k=photo[0]
img4=cv2.imread(k)
plt.imshow(img4)

x=np.array(x)
y=np.array(y)
print(x.shape,y.shape)
x=x/255

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=15,validation_split=0.1)

model.evaluate(x_test,y_test)

plt.plot(history.history['accuracy'])





