# -*- coding: utf-8 -*-
"""butrflay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCiW7YvUrBBtzaHMKMOiM5tHkJguKBc8
"""

import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,MaxPool2D,GlobalAveragePooling2D
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.applications import MobileNetV2
from sklearn.preprocessing import LabelEncoder

path='/content/drive/MyDrive/Dataset/Image_data/butterfly/leedsbutterfly/images'
path2='/content/drive/MyDrive/Dataset/Image_data/butterfly/leedsbutterfly/descriptions'
x=[]
y=[]
for j in os.listdir(path):
  w=j[0:3]+'.txt'
  path_img=os.path.join(path,j)
  path_label=os.path.join(path2,w)
  data=open(path_label,'r')
  data=data.readlines()
  q=data[1]
  img=cv2.imread(path_img)
  img2=cv2.resize(img,(128,128))
  img2=img2/255
  x.append(img2)
  y.append(q)

la=LabelEncoder()
y=la.fit_transform(y)

x=np.array(x)
y=np.array(y)
print(x.shape,y.shape)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

# base_model=MobileNetV2(weights='imagenet',include_top=False,input_shape=(224,224,3))
# for layer in base_model.layers[:-5]:
#   layer.trainable=False
# for layer in base_model.layers[-5:]:
#   layer.trainable=True

# model=Sequential([base_model,GlobalAveragePooling2D()])
# model.add(Dense(128,activation='relu'))
# model.add(Flatten())
# model.add(Dense(64,activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(10,activation='softmax'))
# model.summary()

model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=50,validation_split=0.1)

model.evaluate(x_test,y_test)

plt.plot(history.history['accuracy'])

