# -*- coding: utf-8 -*-
"""Deep 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jVH8iwISshqSFQjhyzlK9AaInx0UnR5
"""

from sklearn import datasets
import numpy as np
import re
from sklearn.feature_extraction.text import CountVectorizer
from joblib import dump,load
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense,Conv2D,Embedding,Input
import numpy as np
import cv2
import pandas as pd
import seaborn as sb
import seaborn as sns
from sklearn import *
from sklearn import tree
from sklearn import datasets
import matplotlib.pyplot as plt
from seaborn import load_dataset
from sklearn.metrics import r2_score
from sklearn.model_selection import *
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfVectorizer
from joblib import dump, load
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale,minmax_scale,normalize
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

data=datasets.fetch_20newsgroups(categories=['alt.atheism',
    'comp.graphics',
    'comp.os.ms-windows.misc',
    'comp.sys.ibm.pc.hardware',
    'comp.sys.mac.hardware',
    'comp.windows.x'])

data.keys()

x=data['data']

import re

def clean(text):
    # حذف header ها
    text = re.sub(
        r'^(From:|Subject:|Nntp-Posting-Host:|Organization:|X-Newsreader:|Lines:).*$',
        '',
        text,
        flags=re.MULTILINE
    )

    # حذف خطوط نقل قول (> یا |)
    text = re.sub(r'^\s*[>|].*$', '', text, flags=re.MULTILINE)

    # حذف "xxx wrote:"
    text = re.sub(r'^.*wrote:.*$', '', text, flags=re.MULTILINE)

    # ❗ حذف signature (خیلی مهم)
    # هر چیزی بعد از -- یا ___ یا ...
    text = re.split(r'\n\s*--+\s*\n', text)[0]

    # حذف ایمیل‌ها
    text = re.sub(r'\S+@\S+', '', text)

    # حذف URL
    text = re.sub(r'http\S+|www\.\S+', '', text)

    # حذف خطوط خیلی کوتاه (مثل h+ یا ---)
    text = re.sub(r'^\s*\W*\s*$', '', text, flags=re.MULTILINE)

    # حذف کاراکترهای اضافی
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # حذف فاصله‌های اضافه
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

x_clean=list(map(clean,x))
text=x_clean[3]
text

c=CountVectorizer()
f=c.fit_transform(x_clean)
dump(c,'b.joblib')

x=f
y=data['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

model=Sequential()
model.add(Dense(50,activation='relu',input_shape=(x_train.shape[1],)))
model.add(Dense(6,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=25,validation_split=0.1)

model.evaluate(x_test,y_test)

x1=['My MacBook fan is making loud noise.']
o=load('b.joblib')
x2=o.transform(x1)
y_pre2=model.predict(x2)
e=np.argmax(y_pre2)
e

data['target']

data['target_names']

import pandas as pd
data = pd.read_csv('/content/cleaned_snappfood.csv')
data.head()

data.drop(columns=['comment','comment_length'],inplace=True)
data

u=data['comment_cleaned']

from sklearn.feature_extraction.text import TfidfVectorizer
v=TfidfVectorizer()
x=v.fit_transform(u)
dump(v,'g.joblib')

y=data['label']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

model=Sequential()
model.add(Dense(50,activation='relu',input_shape=(x_train.shape[1],)))
model.add(Dense(2,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=25,validation_split=0.1)

model.evaluate(x_test,y_test)

x1=['غذا خوب بود']
o=load('/content/g.joblib')
x2=o.transform(x1)
y_pre2=model.predict(x2)
y_pre2

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Dataset/CSV_data/cleaned_snappfood.csv')
data.head()

d=data['comment_cleaned']
q=set()
for i in d:
  w=i.split()
  for e in w:
    q.add(e)
di=dict()
for r,j in enumerate(q):
  di.update({j:r})
di

x=[]
d=data['comment_cleaned']
for i in d:
  w=i.split()
  s=[]
  for e in w:
    num=di[e]
    s.append(num)
  x.append(s)

from tensorflow.keras.preprocessing.sequence import pad_sequences
x=pad_sequences(x,padding='post')
y=data['label']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

model=Sequential()
vocab_size=len(di)+1
max_len=x_train.shape[1]
model.add(Input(shape=(max_len,)))
model.add(Embedding(input_dim=vocab_size, output_dim=64, input_length=max_len))
model.add(Dense(50,activation='relu',input_shape=(x_train.shape[1],)))
model.add(Dense(2,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=15,validation_split=0.1)

model.evaluate(x_test,y_test)

x1=['غذا بد بود']
h=[]
for i in x1[0].split():
  if i in di:
    h.append(di[i])
x2 = pad_sequences([h],maxlen=x_train.shape[1],padding='post')
y_pre2=model.predict(x2)
np.argmax(y_pre2)



