# -*- coding: utf-8 -*-
"""Deep6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyLFu3AlsAE4xm65v65sjdG9bqStebMP
"""

import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout

path='/content/drive/MyDrive/Dataset/Image_data/age'
list_img=[]
x=[]
y=[]
for q in os.listdir(path):
  list_img.append(q)
for i,j in enumerate(list_img):
  path2=f'/content/drive/MyDrive/Dataset/Image_data/age/{j}'
  for w in os.listdir(path2):
    path3=os.path.join(path2,w)
    for t in os.listdir(path3):
      path4=os.path.join(path3,t)
      img=cv2.imread(path4)
      img2=cv2.resize(img,(128,128))
      x.append(img2)
      y.append(i)

x=np.array(x)
y=np.array(y)
x=x/255.0

from google.colab import drive
drive.mount('/content/drive')

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

model=Sequential()
model.add(Conv2D(32,(3,3),padding='same',activation='relu',input_shape=(128,128,3)))
model.add(MaxPool2D(2,2))
model.add(Dropout(0.25))
model.add(Conv2D(32,(3,3),padding='same',activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(21,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=25,validation_split=0.1)

model.evaluate(x_test,y_test)

history.history.keys()

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

plt.plot(history.history['accuracy'])

