# -*- coding: utf-8 -*-
"""Kaggle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk-M-1qzGWZ4mGwL6woC0WmNqfYO_Ccf
"""

import cv2
! pip install kaggle
from kaggle.api.kaggle_api_extended import KaggleApi
import os

os.environ['KAGGLE_USERNAME']='mattinmoradi2025'
os.environ['KAGGLE_KEY']='2eb06f0c139a78c4e5846e112873b3b1'
dataset_name='lakshmi25npathi/imdb-dataset-of-50k-movie-reviews'
download_path='/content/drive/MyDrive/Dataset/CSV_data'
api=KaggleApi()
api.authenticate()
api.dataset_download_files(dataset_name,path=download_path,unzip=True)

