# -*- coding: utf-8 -*-
"""Deep 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9NsabuuBukOsNq7WlD4pBFbucx8DGbW
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
data = pd.read_csv('/content/drive/MyDrive/Dataset/CSV_data/IMDB Dataset.csv')
data.head()

la=LabelEncoder()
data['sentiment']=la.fit_transform(data['sentiment'])
data

import re
def clean(text):
    # حذف header ها
    text = re.sub(
        r'^(From:|Subject:|Nntp-Posting-Host:|Organization:|X-Newsreader:|Lines:).*$',
        '',
        text,
        flags=re.MULTILINE
    )

    # حذف خطوط نقل قول (> یا |)
    text = re.sub(r'^\s*[>|].*$', '', text, flags=re.MULTILINE)

    # حذف "xxx wrote:"
    text = re.sub(r'^.*wrote:.*$', '', text, flags=re.MULTILINE)

    # ❗ حذف signature (خیلی مهم)
    # هر چیزی بعد از -- یا ___ یا ...
    text = re.split(r'\n\s*--+\s*\n', text)[0]

    # حذف ایمیل‌ها
    text = re.sub(r'\S+@\S+', '', text)

    # حذف URL
    text = re.sub(r'http\S+|www\.\S+', '', text)

    # حذف خطوط خیلی کوتاه (مثل h+ یا ---)
    text = re.sub(r'^\s*\W*\s*$', '', text, flags=re.MULTILINE)

    # حذف کاراکترهای اضافی
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # حذف فاصله‌های اضافه
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

e=data['review']
x_clean=list(map(clean,e))
dd=x_clean[30]
dd





d=x_clean
q=set()
for i in d:
  w=i.split()
  for e in w:
    q.add(e)
di=dict()
for r,j in enumerate(q):
  di.update({j:r})
di

x=[]
d=x_clean
for i in d:
  w=i.split()
  s=[]
  for e in w:
    if e in di:
      num=di[e]
      s.append(num)
  x.append(s)

len(x[0])

from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
x=pad_sequences(x,padding='post')
y=data['sentiment']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

from keras.models import Sequential
from keras.layers import Dense,Conv2D,Embedding,Input
model=Sequential()
model.add(Dense(50,activation='relu',input_shape=(x_train.shape[1],)))
model.add(Dense(2,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=25,validation_split=0.1)

model.evaluate(x_test,y_test)

import numpy as np
x1=['this movie is good']
h=[]
for i in x1[0].split():
  if i in di:
    h.append(di[i])
x2=pad_sequences([h],maxlen=x_train.shape[1],padding='post')
y_pre2=model.predict(x2)
np.argmax(y_pre2)

!pip install nltk

from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
from sklearn.preprocessing import LabelEncoder
data = pd.read_csv('/content/drive/MyDrive/Dataset/CSV_data/IMDB Dataset.csv')
data.head()

import re
def clean(text):
    # حذف header ها
    text = re.sub(
        r'^(From:|Subject:|Nntp-Posting-Host:|Organization:|X-Newsreader:|Lines:).*$',
        '',
        text,
        flags=re.MULTILINE
    )

    # حذف خطوط نقل قول (> یا |)
    text = re.sub(r'^\s*[>|].*$', '', text, flags=re.MULTILINE)

    # حذف "xxx wrote:"
    text = re.sub(r'^.*wrote:.*$', '', text, flags=re.MULTILINE)

    # ❗ حذف signature (خیلی مهم)
    # هر چیزی بعد از -- یا ___ یا ...
    text = re.split(r'\n\s*--+\s*\n', text)[0]

    # حذف ایمیل‌ها
    text = re.sub(r'\S+@\S+', '', text)

    # حذف URL
    text = re.sub(r'http\S+|www\.\S+', '', text)

    # حذف خطوط خیلی کوتاه (مثل h+ یا ---)
    text = re.sub(r'^\s*\W*\s*$', '', text, flags=re.MULTILINE)

    # حذف کاراکترهای اضافی
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # حذف فاصله‌های اضافه
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

e=data['review']
x_clean=list(map(clean,e))
dd=x_clean[30]
dd

t=Tokenizer()
t.fit_on_texts(x_clean)
r=t.texts_to_sequences(x_clean)
len(t.index_word)

print(r[0])

import numpy as np
encoder=OneHotEncoder(sparse_output=False)
data['sentiment']=encoder.fit_transform(data['sentiment'].values.reshape(-1,1))
data

from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
x=pad_sequences(r,padding='post')
y=data['sentiment']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

x[0].size

from keras.models import Sequential
from keras.layers import Dense,Conv2D,Embedding,LSTM,Input
model=Sequential()
model.add(Input(shape=(2514,)))
model.add(Embedding(input_dim=99246,output_dim=3))
model.add(LSTM(32))
model.add(Dense(2,activation='softmax'))
model.summary()

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,epochs=5,validation_split=0.1)

model.evaluate(x_test,y_test)

import numpy as np
x1=['this movie is not good']
t=Tokenizer()
t.fit_on_texts(x1)
r=t.texts_to_sequences(x1)
x2=pad_sequences(r,maxlen=x_train.shape[1],padding='post')
y_pre2=model.predict(x2)
np.argmax(y_pre2)







