# -*- coding: utf-8 -*-
"""number_plate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAxo5IS6aDm_G68TVrxhqgpXA3tcR63H
"""

!cp -r "/content/drive/MyDrive/Dataset/Image_data/number_plate/1000-YoloDataset/1000-YoloDataset" "/content/plate_irani_local"

import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,MaxPool2D,GlobalAveragePooling2D
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.applications import MobileNetV2
from sklearn.preprocessing import LabelEncoder

path=r'/content/plate_irani_local/images'
path2=r'/content/plate_irani_local/labels'
x=[]
y=[]
for i in os.listdir(path):
    if i.endswith('JPG'):
        path_img=os.path.join(path,i)
        img=cv2.imread(path_img)
        h,w,_=img.shape
        img2=cv2.resize(img,(128,128))
        label=i[0:-4]+'.txt'
        path_label=os.path.join(path2,label)
        with open(path_label,'r') as f:
            Label=f.readlines()
            for m in Label:
                data_label=m.strip().split()
                if not data_label:
                    continue
                point=[]
                for e in range(1,len(data_label),2):
                    if e==3:
                        continue
                    if (e+1)>=len(data_label):
                        continue
                    x1=int(float(data_label[e])*w)
                    y1=int(float(data_label[e+1])*h)
                    point.append([x1,y1])
                if len(point)>=4:
                    d=np.array(point)
                    r=cv2.minAreaRect(d)
                    box=cv2.boxPoints(r)
                    box_n=[]
                    for p in box:
                        x_n=p[0]/w
                        y_n=p[1]/h
                        box_n.append(x_n)
                        box_n.append(y_n)
                        x.append(img2)
                        y.append(box_n)

x=np.array(x)
y=np.array(y)
x=x/255

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

# base_model=MobileNetV2(weights='imagenet',include_top=False,input_shape=(128,128,3))
# for layer in base_model.layers:
#   layer.trainable=False

# model=Sequential([base_model])
# model.add(Flatten())
# model.add(Dense(128,activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(8,activation='sigmoid'))
# model.summary()

model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(256,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
# model.add(Conv2D(512,(3,3),activation='relu'))
# model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(8,activation='sigmoid'))
model.summary()

model.compile(optimizer='adam',loss='mse',metrics=['mae'])

history=model.fit(x_train,y_train,epochs=35,validation_split=0.1)

model.evaluate(x_test,y_test)

accuracy=1-np.array(history.history['mae'])
plt.plot(accuracy)









file_name = '20240425_083230'
img_path=f'/content/plate_irani_local/images/{file_name}.JPG'
img2=cv2.imread(img_path)
h,w,_=img2.shape
test=cv2.resize(img2,(128,128))/255
label=np.expand_dims(test,axis=0)
label2=model.predict(label)[0]
label3=[]
for i in range(0, 8, 2):
    x1=int(label2[i]*w)
    y1=int(label2[i+1]*h)
    label3.append([x1,y1])
label3=np.array(label3,dtype=np.int32)
rect = cv2.minAreaRect(label3)
box = cv2.boxPoints(rect)
box = np.array(box, dtype=np.int32)
cv2.drawContours(img2, [box], 0, (0, 255, 0), 3)
plt.imshow(img2[...,::-1])

