# -*- coding: utf-8 -*-
"""yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXUy_ECwxGx1H9IZpmliXf7PVQK6MPsU
"""

!cp -r "/content/drive/MyDrive/Dataset/Image_data/caryolo" "/content/plate_yolo_local"

!pip install ultralytics
from ultralytics import YOLO
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

model=YOLO('yolo11n.pt')
res=model('/content/soren.jpg')
r=res[0]
img=r.plot()
plt.imshow(img[...,::-1])

model=YOLO('yolo11n.pt')
model.train(data='/content/Data2.yaml',
            epochs=5,
            project='/content/model',
            name='my_model')

model=YOLO('yolo11n.pt')
model.train(data='/content/dron.yaml',
            epochs=5,
            project='/content/model3',
            name='my_model2')

model=YOLO('yolo26n-seg.pt')
res=model('1751022918259.7976o01.jpg')
r=res[0]
img=r.plot()
plt.imshow(img[...,::-1])

